version: '3'
services:
  postgres-service:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crud
  redis-service:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  rabbitmq-service:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"